name: build
on:
  push:
    branches:
      - 'master'      

jobs:
  ci:
    uses: quenktechnologies/.github/.github/workflows/node.yml@master
    secrets: inherit
    with:
      target: build_release
